#!/usr/bin/env bash
set -euo pipefail

script_dir=$(CDPATH= cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
repo_root=$(CDPATH= cd "$script_dir/.." && pwd)
cd "$repo_root"

AGENTS_DIR="${AGENTS_DIR:-$repo_root/.agents}"

render_target() {
  local title=$1
  local extra_file=$2
  local target=$3

  mkdir -p "$(dirname "$target")"
  {
    printf "%s\n" "# $title"
    printf "%s\n" ""
    printf "%s\n" "<!-- Generated by .agents/render.sh. Edit .agents/global.md or .agents/${extra_file}, then rerun .agents/render.sh. -->"
    printf "%s\n" ""
    printf "%s\n" "## Shared Instructions"
    printf "%s\n" ""
    sed -n "/^# /!p" "$AGENTS_DIR/global.md"
    printf "%s\n" ""
    printf "%s\n" "## Tool-Specific Instructions"
    printf "%s\n" ""
    sed -n "/^# /!p" "$AGENTS_DIR/$extra_file"
  } > "$target"
}

render_target "Codex Instructions" "codex-extra.md" "$repo_root/AGENTS.md"
render_target "Claude Instructions" "claude-extra.md" "$repo_root/CLAUDE.md"

printf "Rendered %s\n" "$repo_root/AGENTS.md"
printf "Rendered %s\n" "$repo_root/CLAUDE.md"
